version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: online-book-store
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
        "spring.datasource.username": "$MYSQL_USERNAME",
        "spring.datasource.password": "$MYSQL_ROOT_PASSWORD",
        "jwt.secret": "$JWT_SECRET"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
